<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Kamba')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'])
                        ->prependStylesheet($this->basePath() . '/css/kamba.css')
                        ->prependStylesheet($this->basePath() . '/css/nprogress.css')
                        ->prependStylesheet($this->basePath() . '/css/chosen.min.css')
                        ->prependStylesheet($this->basePath() . '/css/chosen-bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery.gritter.css')
                        ->prependStylesheet($this->basePath() . '/css/DT_bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <?php echo $this->headScript()
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', ['conditional' => 'lt IE 9',])
                ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', ['conditional' => 'lt IE 9',])
        ; ?>

    </head>
    <body>
        <?php echo $this->flashMessenger()->render('success', ['gritter-success']) ?>
        <?php echo $this->flashMessenger()->render('warning', ['gritter-warning']) ?>
        <?php echo $this->flashMessenger()->render('error', ['gritter-danger']) ?>
        <?php echo $this->globalMessenger()->render() ?>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".header-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="<?php echo $this->url('index', [], [], true) ?>" class="logo navbar-brand">Kamba <span class="version">/ 0.1.0</span></a>
                </div>
                <?php if ($user = $this->identity()): ?>
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" tabindex="91" href="#" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>
                            <?php echo $user->getName() ?>
                            <strong class="caret"></strong>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#" tabindex="92"><i class="glyphicon glyphicon-user"></i> <?php echo $user->getLogin() ?></a></li>
                            <li><a href="" tabindex="93" id="refresh-cache"><i class="glyphicon glyphicon-trash"></i> <?php echo $this->translate('Refresh cache') ?></a></li>
                            <li><a href="<?php echo $this->url('signout') ?>" tabindex="94"><i class="glyphicon glyphicon-off"></i> <?php echo $this->translate('Signout') ?></a></li>
                        </ul>
                    </li>
                </ul>
                <form class="form-inline pull-right" role="form" id="current-environment-form">
                    <div class="form-group">
                        <select id="current-environment" tabindex="90" class="form-control" name="env" data-placeholder="<?php echo $this->translate('Select an environment') ?>" data-rel="chosen" style="display: none;">
                            <option></option>
                            <option value="0"><?php echo $this->translate('All') ?></option>
                            <?php echo $this->environmentSelect('readEnv', true) ?>
                        </select>
                    </div>
                </form>
                <?php endif ?>
                <div class="collapse navbar-collapse header-collapse">
                    <?php echo $this->navigation()->menu('navbar')->setUlClass('nav navbar-nav')->setPartial('layout/partial.menu.phtml')->renderPartial(); ?>
                </div>
            </div>
        </div>
        <div class="container tab-content">
            <div>
                <?php $breadcrumb = $this->navigation()->breadcrumbs('breadcrumb')->setSeparator('<span class="glyphicon glyphicon-chevron-right btn-xs lightgrey"></span>')->render(); ?>
                <?php echo $breadcrumb ? $breadcrumb . '<hr />' : ''; ?>
            </div>
<?php echo $this->content; ?>
        </div> <!-- /container -->
        <!-- Scripts -->
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath() . '/js/kmb.constants.js')
            ->prependFile($this->basePath() . '/js/kamba.js')
            ->prependFile($this->basePath() . '/js/nprogress.js')
            ->prependFile($this->basePath() . '/js/jquery.flot.stack.js')
            ->prependFile($this->basePath() . '/js/jquery.flot.js')
            ->prependFile($this->basePath() . '/js/jquery.chosen.min.js')
            ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/jquery.gritter.min.js')
            ->prependFile($this->basePath() . '/js/jquery.knob.js')
            ->prependFile($this->basePath() . '/js/dataTables.bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.dataTables.min.js')
            ->prependFile($this->basePath() . '/js/jquery.jeditable.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery-2.1.3.min.js')
        ; ?>
    </body>
</html>
